services:
  chirpstack:
    image: chirpstack/chirpstack:latest
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - "8080:8080"

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:latest
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
    volumes:
      - ./chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto

  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:latest
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    ports:
      - "3001:3001"
    volumes:
      - ./chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:latest
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:alpine
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
    networks:
      - default
      - monitoring

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:latest-dev
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - "8888:8888"
    environment:
      - TZ=Europe/Paris
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_74a0fcafa4f3ef11a31cc51b6d9880ab-if00-port0:/dev/ttyUSB0
    networks:
      - monitoring

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro # Mount the Telegraf configuration file
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount the Docker socket to collect Docker metrics
    depends_on:
      - influxdb2
    links:
      - influxdb2
    ports:
      - "8125:8125" # Expose Telegraf's StatsD port
    networks:
      - monitoring # Connect the Telegraf container to the monitoring network

  influxdb2:
    image: influxdb:2-alpine
    container_name: influxdb2
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086" # Expose InfluxDB on port 8086
    volumes:
      - influxdb_data:/var/lib/influxdb2 # Mount the InfluxDB data directory
    networks:
      - monitoring # Connect the InfluxDB container to the monitoring network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb2
    ports:
      - "3000:3000" # Expose Grafana on port 3000
    volumes:
      - grafana_data:/var/lib/grafana # Mount the Grafana data directory
    networks:
      - monitoring # Connect the Grafana container to the monitoring network

  node-red:
    image: nodered/node-red:latest-minimal
    environment:
      - TZ=Europe/Paris
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    networks:
      - monitoring

volumes:
  postgresqldata:
  redisdata:
  grafana_data: {} # Volume for Grafana data
  influxdb_data: {} # Volume for InfluxDB data
  node-red-data:

networks:
  monitoring:
    external: true # Use an external network named 'monitoring'
